export const Data = [{
  'Title': 'Blade Runner',
  'Year': '1982',
  'Rated': 'R',
  'Released': '25 Jun 1982',
  'Runtime': '117 min',
  'Genre': 'Action, Sci-Fi, Thriller',
  'Director': 'Ridley Scott',
  'Writer': 'Hampton Fancher (screenplay), David Webb Peoples',
  'Actors': 'Harrison Ford, Rutger Hauer, Sean Young, Edward James Olmos',
  'Plot': 'In the futuristic year of 2019, Los Angeles has ',
  'Country': 'USA',
  'Awards': 'Nominated for 2 Oscars. Another 12 wins & 17 nominations.',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BNzQzMzJhZTEtOWM4NS00MTdhLTg0YjgtMjM4MDRkZjUwZDBlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
  'Ratings': [
    {
      'Source': 'Internet Movie Database',
      'Value': '8.1/10',
    },
    {
      'Source': 'Rotten Tomatoes',
      'Value': '90%',
    },
    {
      'Source': 'Metacritic',
      'Value': '84/100',
    },
  ],
  'Metascore': '84',
  'imdbRating': '8.1',
  'imdbVotes': '698,571',
  'imdbID': 'tt0083658',
  'Type': 'movie',
  'DVD': '15 Nov 2016',
  'BoxOffice': '$32,868,943',
  'Production': 'Ladd Company, Blade Runner Partnership',
  'Website': 'N/A',
  'Response': 'True',
},
{
  'Title': 'Blade Runner 2',
  'Year': '1982',
  'Rated': 'R',
  'Released': '25 Jun 1982',
  'Runtime': '117 min',
  'Genre': 'Action, Sci-Fi, Thriller',
  'Director': 'Ridley Scott',
  'Writer': 'Hampton Fancher (screenplay), David Webb Peoples',
  'Actors': 'Harrison Ford, Rutger Hauer, Sean Young, Edward James Olmos',
  'Plot': 'In the futuristic year of 2019, Los Angeles has ',
  'Country': 'USA',
  'Awards': 'Nominated for 2 Oscars. Another 12 wins & 17 nominations.',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BNzQzMzJhZTEtOWM4NS00MTdhLTg0YjgtMjM4MDRkZjUwZDBlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
  'Ratings': [
    {
      'Source': 'Internet Movie Database',
      'Value': '8.1/10',
    },
    {
      'Source': 'Rotten Tomatoes',
      'Value': '90%',
    },
    {
      'Source': 'Metacritic',
      'Value': '84/100',
    },
  ],
  'Metascore': '84',
  'imdbRating': '8.1',
  'imdbVotes': '698,571',
  'imdbID': 'tt0083659',
  'Type': 'movie',
  'DVD': '15 Nov 2016',
  'BoxOffice': '$32,868,943',
  'Production': 'Ladd Company, Blade Runner Partnership',
  'Website': 'N/A',
  'Response': 'True',
},
{
  'Title': 'Blade Runner 2',
  'Year': '1982',
  'Rated': 'R',
  'Released': '25 Jun 1982',
  'Runtime': '117 min',
  'Genre': 'Action, Sci-Fi, Thriller',
  'Director': 'Ridley Scott',
  'Writer': 'Hampton Fancher (screenplay), David Webb Peoples',
  'Actors': 'Harrison Ford, Rutger Hauer, Sean Young, Edward James Olmos',
  'Plot': 'In the futuristic year of 2019, Los Angeles has ',
  'Country': 'USA',
  'Awards': 'Nominated for 2 Oscars. Another 12 wins & 17 nominations.',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BNzQzMzJhZTEtOWM4NS00MTdhLTg0YjgtMjM4MDRkZjUwZDBlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
  'Ratings': [
    {
      'Source': 'Internet Movie Database',
      'Value': '8.1/10',
    },
    {
      'Source': 'Rotten Tomatoes',
      'Value': '90%',
    },
    {
      'Source': 'Metacritic',
      'Value': '84/100',
    },
  ],
  'Metascore': '84',
  'imdbRating': '8.1',
  'imdbVotes': '698,571',
  'imdbID': 'tt0083660',
  'Type': 'movie',
  'DVD': '15 Nov 2016',
  'BoxOffice': '$32,868,943',
  'Production': 'Ladd Company, Blade Runner Partnership',
  'Website': 'N/A',
  'Response': 'True',
},
{
  'Title': 'Blade Runner 2',
  'Year': '1982',
  'Rated': 'R',
  'Released': '25 Jun 1982',
  'Runtime': '117 min',
  'Genre': 'Action, Sci-Fi, Thriller',
  'Director': 'Ridley Scott',
  'Writer': 'Hampton Fancher (screenplay), David Webb Peoples',
  'Actors': 'Harrison Ford, Rutger Hauer, Sean Young, Edward James Olmos',
  'Plot': 'In the futuristic year of 2019, Los Angeles has ',
  'Country': 'USA',
  'Awards': 'Nominated for 2 Oscars. Another 12 wins & 17 nominations.',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BNzQzMzJhZTEtOWM4NS00MTdhLTg0YjgtMjM4MDRkZjUwZDBlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
  'Ratings': [
    {
      'Source': 'Internet Movie Database',
      'Value': '8.1/10',
    },
    {
      'Source': 'Rotten Tomatoes',
      'Value': '90%',
    },
    {
      'Source': 'Metacritic',
      'Value': '84/100',
    },
  ],
  'Metascore': '84',
  'imdbRating': '8.1',
  'imdbVotes': '698,571',
  'imdbID': 'tt0083661',
  'Type': 'movie',
  'DVD': '15 Nov 2016',
  'BoxOffice': '$32,868,943',
  'Production': 'Ladd Company, Blade Runner Partnership',
  'Website': 'N/A',
  'Response': 'True',
}];

